#!/usr/bin/env bash
set -e

ENV_FILE="app/.env"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists"
else
  echo "Creating $ENV_FILE"
  cat <<EOT > "$ENV_FILE"
OPENAI_API_KEY=${OPENAI_API_KEY}
SERP_KEY=${SERP_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
GOOGLE_CX=${GOOGLE_CX}
UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
COSMOS_KEY=${COSMOS_KEY}
COSMOS_DB_NAME=${COSMOS_DB_NAME}
COSMOS_CONTAINER_NAME=${COSMOS_CONTAINER_NAME}
PORT=${PORT}
EOT
fi

